// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90eze5wKojfp6D8b1agO2VIH-_lSfntc',
    appId: '1:367172964905:web:b5c335c82ce9f238404238',
    messagingSenderId: '367172964905',
    projectId: 'pockettrack-629e7',
    authDomain: 'pockettrack-629e7.firebaseapp.com',
    storageBucket: 'pockettrack-629e7.firebasestorage.app',
    measurementId: 'G-ZBTZ52J7S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsjF6JwHgNIOt9TO2nQYW46KEFTy-IXzs',
    appId: '1:367172964905:android:9bf5d7d97e1e0c60404238',
    messagingSenderId: '367172964905',
    projectId: 'pockettrack-629e7',
    storageBucket: 'pockettrack-629e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCLf5N8Yn0HcTVBPFyed57W0GoXm1YwI',
    appId: '1:367172964905:ios:c3f5c1c65370be9c404238',
    messagingSenderId: '367172964905',
    projectId: 'pockettrack-629e7',
    storageBucket: 'pockettrack-629e7.firebasestorage.app',
    iosBundleId: 'com.example.pockettrack',
  );
}
